apiVersion: cluster.clusterpedia.io/v1alpha2
kind: PediaCluster
metadata:
  labels:
    upm.io/owner: "upm"
    upm.io/workload: "true"
  name: upm-workload-cluster
spec:
  apiserver: "${workload_apiserver}"
  kubeconfig: "${workload_kubeconfig_encode}"
  syncResourcesRefName: "global-base"
  syncResources: []
  syncAllCustomResources: true