apiVersion: cluster.clusterpedia.io/v1alpha2
kind: PediaCluster
metadata:
  labels:
    upm.io/owner: "upm"
    upm.io/manager: "true"
  name: upm-manager-cluster
spec:
  apiserver: "${manager_apiserver}"
  kubeconfig: "${manager_kubeconfig_encode}"
  syncResourcesRefName: "global-base"
  syncResources: []