apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: redis
    meta.helm.sh/release-namespace: "${REDIS_KUBE_NAMESPACE}"
  labels:
    app.kubernetes.io/component: master
    app.kubernetes.io/instance: redis
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: redis
    app.kubernetes.io/version: "${APP_VERSION}"
    helm.sh/chart: "redis-${VERSION}"
  name: redis
  namespace: "${REDIS_KUBE_NAMESPACE}"
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: tcp-redis
      nodePort: 32007
      port: ${REDIS_PORT}
      protocol: TCP
      targetPort: redis
  selector:
    app.kubernetes.io/component: master
    app.kubernetes.io/instance: redis
    app.kubernetes.io/name: redis
  sessionAffinity: None
  type: NodePort